pipeline {

    agent any

    environment {
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {

        stage('Checkout') {
            steps {
                git url: 'https://github.com/VenkatBheemireddy/jenkins-projects.git',
                    branch: 'main'
            }
        }

        stage('Build Java with Maven Container') {
            agent {
                docker {
                    image 'maven:3.9.9-eclipse-temurin-17'
                    args '-v $HOME/.m2:/root/.m2'
                }
            }

            steps {
                dir('hello-world/java-app') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Run Java App') {
            agent {
                docker {
                    image 'openjdk:17'
                }
            }

            steps {
                dir('hello-world/java-app') {
                    sh 'java -cp target/classes com.example.HelloWorld'
                }
            }
        }

        stage('Run NodeJS App') {
            agent {
                docker {
                    image 'node:20'
                }
            }

            steps {
                dir('hello-world/node-app') {
                    sh '''
                    npm install
                    npm start
                    '''
                }
            }
        }

    }
}
